import "./globals.css";

import Navbar from "@/components/Navbar";

export const metadata = {
  title: "Anime App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <>
      <html lang="en">
        <body className="">
          <div className="main">
            <div className="gradient"></div>
          </div>

          <main className="app">
            <Navbar />
            {children}
          </main>
        </body>
      </html>
    </>
  );
};

export default RootLayout;
